apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    cource: docker
    duration: 25hr
    trainer: siva
  annotations:
    org.docker.kubernetes.maintainer: siva
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
