apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    cource: docker
    duration: 25hr
    trainer: siva
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
