apiVersion: v1
kind: pod
metadata:
  name: probe
spec:
  containers:
  - image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
    name: nginx
