apiVersion: v1
kind: pod
metadata:
 name: probe
spec:
 containers:
 -image: nginx
  name: nginx
  livenessProbe:
   httpGet:
    path: /
    port: 80
   initialDelaySeconds: 3
   periodSeconds: 5
